[package]
name = "optdbg"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.35", features = ["derive"] }
datafusion = "45"
optd-core = { path = "./optd/optd-core" }
chrono = "0.4.39"
optd-datafusion = { path = "./optd/optd-datafusion" }
tokio = { version = "1.44.2", features = ["full"] }
dolomite = { path = "./datafusion-dolomite/dolomite" }
datafusion-dolomite-integration = { path = "./datafusion-dolomite/datafusion-dolomite-integration/" }


