[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "perfbench"
path = "src/perfbench.rs"

[[bin]]
name = "test"
path = "src/test.rs"

[[bin]]
name = "runner"
path = "src/runner.rs"

[dependencies]
datafusion-common = "46.0.1" # { path = "./datafusion/datafusion/common" }
datafusion-expr = "46.0.1" # { path = "./datafusion/datafusion/expr" }
datafusion-execution = "46.0.1" #{ path = "./datafusion/datafusion/execution" }
datafusion-catalog = "46.0.1" # { path = "./datafusion/datafusion/catalog" }
datafusion = "46.0.1" # { path = "./datafusion/datafusion/core" }
test-utils = { path = "./datafusion/test-utils" }
tokio = { version = "1.44.2", features = ["full"] }
optdbg = { path = "../optdbg" }
anyhow = "1.0.97"
env_logger = "0.11.8"
futures = "0.3.31"
object_store = "0.11.2"
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
clap = { version = "4.5.37", features = ["derive"] }
