mkdir tpch-queries &> /dev/null
mkdir tpch-data &> /dev/null
cd tpch-dbgen
echo "Generating data with dbgen..."
rm *.tbl
make &> /dev/null
./dbgen -s 0.2 &> /dev/null
cp *.tbl ../tpch-data
echo "Generating queries with qgen..."
cp ../tpch-templates/*.sql .
for i in $(seq 22); do
	./qgen -d $i -s 0.2 > ../tpch-queries/$i.sql;
done
# some queries make optd panic
rm ../tpch-queries/7.sql
rm ../tpch-queries/8.sql 
rm ../tpch-queries/9.sql
# some queries have more than one statement
rm ../tpch-queries/15.sql
cd ../tpch-data
echo "Cleaning data generated by dbgen..."
for f in *.tbl; do
	sed -i 's/|$//g' $f
done
cd ../make_parquet
echo "Generating parquet files..."
cargo build --release &> /dev/null
./target/release/make_parquet ../tpch-data 
cd ../tpch-queries
echo "Cleaning queries generated by dbgen..."
grep -rlZ "first -1" . | xargs -0 sed -i 's/first -1//g'
grep -rlZ first . | xargs -0 sed -i 's/first/limit/g'

